name: Cypress
on:
  push:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npm run dev
